"""Added Users table

Revision ID: 138215e6073e
Revises: 4a728240d4e3
Create Date: 2022-04-04 20:10:40.664153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138215e6073e'
down_revision = '4a728240d4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
