"""Added object_barriers table

Revision ID: 19383b6b20a9
Revises: fc064d87aa58
Create Date: 2022-03-29 15:19:57.505255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19383b6b20a9'
down_revision = 'fc064d87aa58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('gsm_number_vp', sa.String(length=50), nullable=True),
    sa.Column('sip_number_vp', sa.String(length=50), nullable=True),
    sa.Column('camera_url', sa.String(length=200), nullable=True),
    sa.Column('camdirect_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_and_address', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_free_departure_prohibited', sa.Boolean(), nullable=False),
    sa.Column('is_free_jkh_passage_prohibited', sa.Boolean(), nullable=False),
    sa.Column('is_free_delivery_passage_prohibited', sa.Boolean(), nullable=False),
    sa.Column('is_free_collection_passage_prohibited', sa.Boolean(), nullable=False),
    sa.Column('is_free_garbtrucks_passage_prohibited', sa.Boolean(), nullable=False),
    sa.Column('is_free_post_passage_prohibited', sa.Boolean(), nullable=False),
    sa.Column('is_free_taxi_passage_prohibited', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_and_address')
    )
    op.create_table('objects_barriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barrier_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barrier_id'], ['barriers.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('published', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    sa.UniqueConstraint('published', name='posts_published_key')
    )
    op.drop_table('objects_barriers')
    op.drop_table('objects')
    op.drop_table('barriers')
    # ### end Alembic commands ###
