"""Added autoincrement and unique attributes

Revision ID: 4a728240d4e3
Revises: 5ff696e8d2c3
Create Date: 2022-03-30 13:53:52.384376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a728240d4e3'
down_revision = '5ff696e8d2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
