"""Added required tables

Revision ID: 971573247181
Revises: 
Create Date: 2022-03-14 22:06:24.685044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971573247181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gsm_number_vp', sa.String(length=50), nullable=True),
    sa.Column('sip_number_vp', sa.String(length=50), nullable=True),
    sa.Column('camera_url', sa.String(length=200), nullable=True),
    sa.Column('camdirect_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_and_address', sa.String(length=100), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_free_departure_prohibited', sa.Boolean(), nullable=True),
    sa.Column('is_free_jkh_passage_prohibited', sa.Boolean(), nullable=True),
    sa.Column('is_free_delivery_passage_prohibited', sa.Boolean(), nullable=True),
    sa.Column('is_free_collection_passage_prohibited', sa.Boolean(), nullable=True),
    sa.Column('is_free_garbtrucks_passage_prohibited', sa.Boolean(), nullable=True),
    sa.Column('is_free_post_passage_prohibited', sa.Boolean(), nullable=True),
    sa.Column('is_free_taxi_passage_prohibited', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_name_and_address'), 'objects', ['name_and_address'], unique=True)
    op.create_table('objects_barriers_links',
    sa.Column('barrier_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barrier_id'], ['barriers.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects_barriers_links')
    op.drop_index(op.f('ix_objects_name_and_address'), table_name='objects')
    op.drop_table('objects')
    op.drop_table('barriers')
    # ### end Alembic commands ###
