"""Added required tables

Revision ID: a9bb797ccf4b
Revises: 6cbf6e5a052e
Create Date: 2022-03-14 23:11:45.667964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9bb797ccf4b'
down_revision = '6cbf6e5a052e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
